services:
    _defaults:
        autoconfigure: true
        autowire: true
    
    Wuapaa\ContaoReviewsBundle\Controller\ContentElement\ReviewsController: ~
    Wuapaa\ContaoReviewsBundle\Controller\FrontendModule\ContaoReviewsFrontendModuleController: ~
    
    App\Controller\ContentElement\MyContentElementController:
        tags:
            -
                name: contao.content_element
                category: texts
                template: ce_my_content_element
                method: getCustomResponse
                renderer: esi
                type: my_custom_type
