services:
    _defaults:
        autoconfigure: true
        autowire: true
    _instanceof:
        Contao\CoreBundle\Framework\FrameworkAwareInterface:
            calls:
                - ["setFramework", ["@contao.framework"]]

        Symfony\Component\DependencyInjection\ContainerAwareInterface:
            calls:
                - ["setContainer", ["@service_container"]] 

    Wuapaa\ContaoReviewsBundle\Controller\ContentElement\ContaoReviewsContentElementController: ~
    Wuapaa\ContaoReviewsBundle\Controller\FrontendModule\ContaoReviewsFrontendModuleController: ~
    
    